/*
 * Translatable string file generated by Glade.
 * Add this file to the project POTFILE.in file.
 * DO NOT compile as part of the appication.
 */

gchar *s = N_("Tor properties");
gchar *s = N_("Tor status: ");
gchar *s = N_("Stopped");
gchar *s = N_("Tor version: ");
gchar *s = N_("n/a");
gchar *s = N_("Uptime: ");
gchar *s = N_("0");
gchar *s = N_("Warnings: ");
gchar *s = N_("Errors: ");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("Log messages:");
gchar *s = N_("Sent:");
gchar *s = N_("Received: ");
gchar *s = N_("Total: ");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("bytes");
gchar *s = N_("bytes");
gchar *s = N_("bytes");
gchar *s = N_("Bandwidth usage:");
gchar *s = N_("Launched: ");
gchar *s = N_("Connected: ");
gchar *s = N_("Failures: ");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("0");
gchar *s = N_("Onion Routers:");
gchar *s = N_("General");
gchar *s = N_("IP Address: ");
gchar *s = N_("Host name: ");
gchar *s = N_("_Resolve");
gchar *s = N_("Tor Resolve");
